## Hard Drive Failure Analytics Analytics - Exploratory Data Analysis
Purpose: The purpose of this notebook is to review the source data and create step by step process and extracting the data from online source and reviewing the data locally

Objectives:
- Extract zipfiles from source
- Uzip files and import CSV files
- Describe data (columns, schema, datatypes, total row count, column count etc.)

In [13]:
import os
import pandas as pd
import requests
import zipfile

Backblaze datasets are organized as the following:
- 2013/2014 - full annual zip file with multiple csv files. Url suffix ends as **data_{year}.zip**
- 2015 and onward - separated as quarterly zip files with multiple csv files (4 quarters for each year). Url suffix ends as **data_{quarter}_{year}.zip**

For testing let's pull just 2013 and see what we have.

In [47]:
# Creating helpful functions

def download_and_extract(zip_url, extract_dir='../data/zip'):    
    # 1. Ensure ./data/zip folder exists
    os.makedirs(extract_dir, exist_ok=True)

    # Get filename from URL path
    zip_filename = zip_url.split('/')[-1] or 'archive.zip'

    # 2. Download zip file from URL and save to extract_dir
    zip_path = os.path.join(extract_dir, zip_filename)
    
    print(f"Downloading {zip_url} to {zip_path}...")
    response = requests.get(zip_url, stream=True)
    response.raise_for_status()  # Raise HTTPError for bad responses
    
    with open(zip_path, 'wb') as f:
        for chunk in response.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)
    
    return zip_path

def unzip_file(input_file, output_dir=f"../data/raw/{year}"):
    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Validate input file exists
    if not os.path.isfile(input_file):
        raise FileNotFoundError(f"Input file does not exist: {input_file}")
    
    with zipfile.ZipFile(input_file, 'r') as zip_ref:
        # List contents (optional check)
        print("Contents:", zip_ref.namelist())
        
        # Extract all files to the specified output directory
        zip_ref.extractall(output_dir)
        print(f"Extracted to: {output_dir}")

In [33]:
output_dir = "./data/zip"
base_url = "https://f001.backblazeb2.com/file/Backblaze-Hard-Drive-Data/"

In [48]:
year = 2025
qtr = "1"
file_suffix = f"{"Q"+qtr}_{year}"
# download_and_extract(base_url+f"data_{file_suffix}.zip")

In [50]:
unzip_file(f"../data/zip/data_{file_suffix}.zip")

Contents: ['data_Q1_2025/2025-01-01.csv', 'data_Q1_2025/2025-01-02.csv', 'data_Q1_2025/2025-01-03.csv', 'data_Q1_2025/2025-01-04.csv', 'data_Q1_2025/2025-01-05.csv', 'data_Q1_2025/2025-01-06.csv', 'data_Q1_2025/2025-01-07.csv', 'data_Q1_2025/2025-01-08.csv', 'data_Q1_2025/2025-01-09.csv', 'data_Q1_2025/2025-01-10.csv', 'data_Q1_2025/2025-01-11.csv', 'data_Q1_2025/2025-01-12.csv', 'data_Q1_2025/2025-01-13.csv', 'data_Q1_2025/2025-01-14.csv', 'data_Q1_2025/2025-01-15.csv', 'data_Q1_2025/2025-01-16.csv', 'data_Q1_2025/2025-01-17.csv', 'data_Q1_2025/2025-01-18.csv', 'data_Q1_2025/2025-01-19.csv', 'data_Q1_2025/2025-01-20.csv', 'data_Q1_2025/2025-01-21.csv', 'data_Q1_2025/2025-01-22.csv', 'data_Q1_2025/2025-01-23.csv', 'data_Q1_2025/2025-01-24.csv', 'data_Q1_2025/2025-01-25.csv', 'data_Q1_2025/2025-01-26.csv', 'data_Q1_2025/2025-01-27.csv', 'data_Q1_2025/2025-01-28.csv', 'data_Q1_2025/2025-01-29.csv', 'data_Q1_2025/2025-01-30.csv', 'data_Q1_2025/2025-01-31.csv', 'data_Q1_2025/2025-02-01.csv', 'data_Q1_2025/2025-02-02.csv', 'data_Q1_2025/2025-02-03.csv', 'data_Q1_2025/2025-02-04.csv', 'data_Q1_2025/2025-02-05.csv', 'data_Q1_2025/2025-02-06.csv', 'data_Q1_2025/2025-02-07.csv', 'data_Q1_2025/2025-02-08.csv', 'data_Q1_2025/2025-02-09.csv', 'data_Q1_2025/2025-02-10.csv', 'data_Q1_2025/2025-02-11.csv', 'data_Q1_2025/2025-02-12.csv', 'data_Q1_2025/2025-02-13.csv', 'data_Q1_2025/2025-02-14.csv', 'data_Q1_2025/2025-02-15.csv', 'data_Q1_2025/2025-02-16.csv', 'data_Q1_2025/2025-02-17.csv', 'data_Q1_2025/2025-02-18.csv', 'data_Q1_2025/2025-02-19.csv', 'data_Q1_2025/2025-02-20.csv', 'data_Q1_2025/2025-02-21.csv', 'data_Q1_2025/2025-02-22.csv', 'data_Q1_2025/2025-02-23.csv', 'data_Q1_2025/2025-02-24.csv', 'data_Q1_2025/2025-02-25.csv', 'data_Q1_2025/2025-02-26.csv', 'data_Q1_2025/2025-02-27.csv', 'data_Q1_2025/2025-02-28.csv', 'data_Q1_2025/2025-03-01.csv', 'data_Q1_2025/2025-03-02.csv', 'data_Q1_2025/2025-03-03.csv', 'data_Q1_2025/2025-03-04.csv', 'data_Q1_2025/2025-03-05.csv', 'data_Q1_2025/2025-03-06.csv', 'data_Q1_2025/2025-03-07.csv', 'data_Q1_2025/2025-03-08.csv', 'data_Q1_2025/2025-03-09.csv', 'data_Q1_2025/2025-03-10.csv', 'data_Q1_2025/2025-03-11.csv', 'data_Q1_2025/2025-03-12.csv', 'data_Q1_2025/2025-03-13.csv', 'data_Q1_2025/2025-03-14.csv', 'data_Q1_2025/2025-03-15.csv', 'data_Q1_2025/2025-03-16.csv', 'data_Q1_2025/2025-03-17.csv', 'data_Q1_2025/2025-03-18.csv', 'data_Q1_2025/2025-03-19.csv', 'data_Q1_2025/2025-03-20.csv', 'data_Q1_2025/2025-03-21.csv', 'data_Q1_2025/2025-03-22.csv', 'data_Q1_2025/2025-03-23.csv', 'data_Q1_2025/2025-03-24.csv', 'data_Q1_2025/2025-03-25.csv', 'data_Q1_2025/2025-03-26.csv', 'data_Q1_2025/2025-03-27.csv', 'data_Q1_2025/2025-03-28.csv', 'data_Q1_2025/2025-03-29.csv', 'data_Q1_2025/2025-03-30.csv', 'data_Q1_2025/2025-03-31.csv']
Extracted to: ../data/raw/2025

In [58]:
pd.set_option('display.max_columns', None) 
df = pd.read_csv(f"../data/raw/{year}/data_{file_suffix}/{year}-01-01.csv", nrows=100)
df.head(10)

,date,serial_number,model,capacity_bytes,failure,datacenter,cluster_id,vault_id,pod_id,pod_slot_num,is_legacy_format,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,smart_3_raw,smart_4_normalized,smart_4_raw,smart_5_normalized,smart_5_raw,smart_7_normalized,smart_7_raw,smart_8_normalized,smart_8_raw,smart_9_normalized,smart_9_raw,smart_10_normalized,smart_10_raw,smart_11_normalized,smart_11_raw,smart_12_normalized,smart_12_raw,smart_13_normalized,smart_13_raw,smart_15_normalized,smart_15_raw,smart_16_normalized,smart_16_raw,smart_17_normalized,smart_17_raw,smart_18_normalized,smart_18_raw,smart_22_normalized,smart_22_raw,smart_23_normalized,smart_23_raw,smart_24_normalized,smart_24_raw,smart_27_normalized,smart_27_raw,smart_71_normalized,smart_71_raw,smart_82_normalized,smart_82_raw,smart_90_normalized,smart_90_raw,smart_160_normalized,smart_160_raw,smart_161_normalized,smart_161_raw,smart_163_normalized,smart_163_raw,smart_164_normalized,smart_164_raw,smart_165_normalized,smart_165_raw,smart_166_normalized,smart_166_raw,smart_167_normalized,smart_167_raw,smart_168_normalized,smart_168_raw,smart_169_normalized,smart_169_raw,smart_170_normalized,smart_170_raw,smart_171_normalized,smart_171_raw,smart_172_normalized,smart_172_raw,smart_173_normalized,smart_173_raw,smart_174_normalized,smart_174_raw,smart_175_normalized,smart_175_raw,smart_176_normalized,smart_176_raw,smart_177_normalized,smart_177_raw,smart_178_normalized,smart_178_raw,smart_179_normalized,smart_179_raw,smart_180_normalized,smart_180_raw,smart_181_normalized,smart_181_raw,smart_182_normalized,smart_182_raw,smart_183_normalized,smart_183_raw,smart_184_normalized,smart_184_raw,smart_187_normalized,smart_187_raw,smart_188_normalized,smart_188_raw,smart_189_normalized,smart_189_raw,smart_190_normalized,smart_190_raw,smart_191_normalized,smart_191_raw,smart_192_normalized,smart_192_raw,smart_193_normalized,smart_193_raw,smart_194_normalized,smart_194_raw,smart_195_normalized,smart_195_raw,smart_196_normalized,smart_196_raw,smart_197_normalized,smart_197_raw,smart_198_normalized,smart_198_raw,smart_199_normalized,smart_199_raw,smart_200_normalized,smart_200_raw,smart_201_normalized,smart_201_raw,smart_202_normalized,smart_202_raw,smart_206_normalized,smart_206_raw,smart_210_normalized,smart_210_raw,smart_211_normalized,smart_211_raw,smart_212_normalized,smart_212_raw,smart_218_normalized,smart_218_raw,smart_220_normalized,smart_220_raw,smart_222_normalized,smart_222_raw,smart_223_normalized,smart_223_raw,smart_224_normalized,smart_224_raw,smart_225_normalized,smart_225_raw,smart_226_normalized,smart_226_raw,smart_230_normalized,smart_230_raw,smart_231_normalized,smart_231_raw,smart_232_normalized,smart_232_raw,smart_233_normalized,smart_233_raw,smart_234_normalized,smart_234_raw,smart_235_normalized,smart_235_raw,smart_240_normalized,smart_240_raw,smart_241_normalized,smart_241_raw,smart_242_normalized,smart_242_raw,smart_244_normalized,smart_244_raw,smart_245_normalized,smart_245_raw,smart_246_normalized,smart_246_raw,smart_247_normalized,smart_247_raw,smart_248_normalized,smart_248_raw,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
0,2025-01-01,2207E60CC65A,CT250MX500SSD1,250059350016,0,sac0,0,1028,13,NaN,False,100,0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,NaN,NaN,100,16790,NaN,NaN,NaN,NaN,100,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,60.0,5.210000e+02,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,27.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63,37,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,60.0,40.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,3.374266e+10,100.0,959739128.0,100.0,1.603481e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-01,2340E87B92B5,CT250MX500SSD1,250059350016,0,sac0,0,1028,14,NaN,False,100,0,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,NaN,NaN,100,3364,NaN,NaN,NaN,NaN,100,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,94.0,7.900000e+01,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,50.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62,38,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,94.0,6.0,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,6.105397e+09,100.0,73589604.0,100.0,1.587336e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-01-01,2EGK64VX,HGST HUH728080ALE604,8001563222016,0,sac0,0,1028,4,12.0,False,100,0,134.0,104.0,236.0,113.0,100.0,66.0,100.0,0.0,100.0,0.0,128.0,18.0,96,32538,100.0,0.0,NaN,NaN,100,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,4364.0,97.0,4364.0,253,23,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,200.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-01,2EHZAKAX,HGST HUH728080ALE604,8001563222016,0,sac0,0,1028,12,30.0,False,100,0,134.0,105.0,155.0,418.0,100.0,23.0,100.0,0.0,100.0,0.0,128.0,18.0,90,71139,100.0,0.0,NaN,NaN,100,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.0,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,2826.0,98.0,2826.0,200,30,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,200.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-01-01,2EJ02A1X,HGST HUH728080ALE604,8001563222016,0,sac0,0,1028,10,14.0,False,100,0,133.0,108.0,151.0,409.0,100.0,22.0,100.0,0.0,100.0,0.0,128.0,18.0,90,71183,100.0,0.0,NaN,NaN,100,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,2839.0,98.0,2839.0,214,28,NaN,NaN,100.0,0.0,100.0,0.0,100.0,0.0,200.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-01-01,7LZ021LA,Seagate BarraCuda SSD ZA250CM10002,250059350016,0,sac0,0,1028,6,NaN,False,100,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,42538,NaN,NaN,NaN,NaN,100,15,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,NaN,NaN,NaN,NaN,100.0,2.022963e+12,100.0,7.0,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,7.0,NaN,NaN,91,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,NaN,NaN,100.0,65786.0,100.0,33891.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2025-01-01,S2ZYJ9CF511681,ST500LM012 HN,500107862016,0,sac0,0,1028,10,NaN,False,100,2815,252.0,0.0,95.0,1798.0,100.0,26.0,252.0,0.0,252.0,0.0,252.0,0.0,100,78798,252.0,0.0,90.0,11102.0,100,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,25.0,252.0,0.0,NaN,NaN,64,35,100.0,0.0,252.0,0.0,252.0,0.0,252.0,0.0,200.0,0.0,100.0,1139950.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,11102.0,NaN,NaN,66.0,352504.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2025-01-01,S2ZYJ9GGB01000,ST500LM012 HN,500107862016,0,sac0,0,1028,0,NaN,False,100,17,252.0,0.0,95.0,1794.0,100.0,11.0,252.0,0.0,252.0,0.0,252.0,0.0,100,62739,252.0,0.0,99.0,1412.0,100,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,37.0,100.0,1.0,NaN,NaN,64,27,100.0,0.0,252.0,0.0,252.0,0.0,252.0,0.0,200.0,0.0,100.0,742264.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.0,1412.0,NaN,NaN,79.0,216860.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2025-01-01,S2ZYJ9GGB01001,ST500LM012 HN,500107862016,0,sac0,0,1028,4,NaN,False,100,2,252.0,0.0,94.0,1830.0,100.0,11.0,252.0,0.0,252.0,0.0,252.0,0.0,100,47676,252.0,0.0,100.0,19.0,100,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,32.0,100.0,2.0,NaN,NaN,64,28,100.0,0.0,252.0,0.0,252.0,0.0,252.0,0.0,200.0,0.0,100.0,55356.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,19.0,NaN,NaN,75.0,259514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2025-01-01,S2ZYJ9GGB01020,ST500LM012 HN,500107862016,0,sac0,0,1028,2,NaN,False,100,60,252.0,0.0,95.0,1779.0,100.0,23.0,252.0,0.0,252.0,0.0,252.0,0.0,100,65007,252.0,0.0,98.0,2682.0,100,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,123.0,100.0,14.0,NaN,NaN,64,29,100.0,0.0,252.0,0.0,252.0,0.0,252.0,0.0,200.0,0.0,100.0,1418913.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.0,2682.0,NaN,NaN,72.0,289776.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
df.columns

Index(['date', 'serial_number', 'model', 'capacity_bytes', 'failure',
       'datacenter', 'cluster_id', 'vault_id', 'pod_id', 'pod_slot_num',
       ...
       'smart_250_normalized', 'smart_250_raw', 'smart_251_normalized',
       'smart_251_raw', 'smart_252_normalized', 'smart_252_raw',
       'smart_254_normalized', 'smart_254_raw', 'smart_255_normalized',
       'smart_255_raw'],
      dtype='str', length=197)

In [59]:
df.shape

(100, 197)

In [60]:
df.describe()

,capacity_bytes,failure,cluster_id,vault_id,pod_id,pod_slot_num,smart_1_normalized,smart_1_raw,smart_2_normalized,smart_2_raw,smart_3_normalized,smart_3_raw,smart_4_normalized,smart_4_raw,smart_5_normalized,smart_5_raw,smart_7_normalized,smart_7_raw,smart_8_normalized,smart_8_raw,smart_9_normalized,smart_9_raw,smart_10_normalized,smart_10_raw,smart_11_normalized,smart_11_raw,smart_12_normalized,smart_12_raw,smart_13_normalized,smart_13_raw,smart_15_normalized,smart_15_raw,smart_16_normalized,smart_16_raw,smart_17_normalized,smart_17_raw,smart_18_normalized,smart_18_raw,smart_22_normalized,smart_22_raw,smart_23_normalized,smart_23_raw,smart_24_normalized,smart_24_raw,smart_27_normalized,smart_27_raw,smart_71_normalized,smart_71_raw,smart_82_normalized,smart_82_raw,smart_90_normalized,smart_90_raw,smart_160_normalized,smart_160_raw,smart_161_normalized,smart_161_raw,smart_163_normalized,smart_163_raw,smart_164_normalized,smart_164_raw,smart_165_normalized,smart_165_raw,smart_166_normalized,smart_166_raw,smart_167_normalized,smart_167_raw,smart_168_normalized,smart_168_raw,smart_169_normalized,smart_169_raw,smart_170_normalized,smart_170_raw,smart_171_normalized,smart_171_raw,smart_172_normalized,smart_172_raw,smart_173_normalized,smart_173_raw,smart_174_normalized,smart_174_raw,smart_175_normalized,smart_175_raw,smart_176_normalized,smart_176_raw,smart_177_normalized,smart_177_raw,smart_178_normalized,smart_178_raw,smart_179_normalized,smart_179_raw,smart_180_normalized,smart_180_raw,smart_181_normalized,smart_181_raw,smart_182_normalized,smart_182_raw,smart_183_normalized,smart_183_raw,smart_184_normalized,smart_184_raw,smart_187_normalized,smart_187_raw,smart_188_normalized,smart_188_raw,smart_189_normalized,smart_189_raw,smart_190_normalized,smart_190_raw,smart_191_normalized,smart_191_raw,smart_192_normalized,smart_192_raw,smart_193_normalized,smart_193_raw,smart_194_normalized,smart_194_raw,smart_195_normalized,smart_195_raw,smart_196_normalized,smart_196_raw,smart_197_normalized,smart_197_raw,smart_198_normalized,smart_198_raw,smart_199_normalized,smart_199_raw,smart_200_normalized,smart_200_raw,smart_201_normalized,smart_201_raw,smart_202_normalized,smart_202_raw,smart_206_normalized,smart_206_raw,smart_210_normalized,smart_210_raw,smart_211_normalized,smart_211_raw,smart_212_normalized,smart_212_raw,smart_218_normalized,smart_218_raw,smart_220_normalized,smart_220_raw,smart_222_normalized,smart_222_raw,smart_223_normalized,smart_223_raw,smart_224_normalized,smart_224_raw,smart_225_normalized,smart_225_raw,smart_226_normalized,smart_226_raw,smart_230_normalized,smart_230_raw,smart_231_normalized,smart_231_raw,smart_232_normalized,smart_232_raw,smart_233_normalized,smart_233_raw,smart_234_normalized,smart_234_raw,smart_235_normalized,smart_235_raw,smart_240_normalized,smart_240_raw,smart_241_normalized,smart_241_raw,smart_242_normalized,smart_242_raw,smart_244_normalized,smart_244_raw,smart_245_normalized,smart_245_raw,smart_246_normalized,smart_246_raw,smart_247_normalized,smart_247_raw,smart_248_normalized,smart_248_raw,smart_250_normalized,smart_250_raw,smart_251_normalized,smart_251_raw,smart_252_normalized,smart_252_raw,smart_254_normalized,smart_254_raw,smart_255_normalized,smart_255_raw
count,1.000000e+02,100.0,100.0,100.0,100.000000,82.000000,100.000000,1.000000e+02,21.000000,21.000000,97.000000,97.000000,97.0,97.000000,99.000000,99.000000,97.000000,9.700000e+01,21.000000,21.000000,100.00000,100.000000,97.000000,97.0,14.000000,14.000000,100.0,100.000000,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,6.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,2.0,2.0,2.0,2.0,3.000000,3.000000e+00,3.0,3.000000,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,2.000000,0.0,0.0,0.0,0.0,2.0,2.0,77.0,77.0,78.000000,78.000000,76.0,76.000000,75.0,75.0,76.000000,76.000000,90.000000,90.000000,98.000000,98.000000,83.000000,83.000000,100.000000,100.000000,90.000000,9.000000e+01,23.000000,23.0,99.000000,99.000000,99.000000,99.0,99.000000,99.0,14.0,1.400000e+01,0.0,0.0,2.000000,2.000000,2.0,2.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,15.000000,15.000000,1.0,1.0,14.000000,14.000000,1.0,1.0,0.0,0.0,1.0,1.000000e+00,1.0,1.000000e+00,1.0,1.0,0.0,0.0,1.0,1.000000e+00,77.0,77.000000,77.0,7.700000e+01,77.0,7.700000e+01,0.0,0.0,0.0,0.0,2.0,2.000000e+00,2.0,2.000000e+00,2.0,2.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,6.643800e+12,0.0,0.0,1028.0,9.810000,22.548780,84.390000,9.398447e+07,210.904762,30.333333,90.113402,285.525773,100.0,13.051546,121.494949,6.303030,113.402062,1.534305e+09,209.333333,5.142857,33.77000,67915.190000,121.938144,0.0,98.428571,1981.428571,100.0,13.030000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,97.833333,97.833333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,84.666667,6.743210e+11,100.0,2.333333,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,38.500000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,99.974359,0.025641,100.0,0.013158,100.0,0.0,69.500000,30.500000,99.944444,673.577778,101.459184,291.112245,99.891566,663.650602,48.260000,30.630000,17.855556,1.044271e+08,192.521739,0.0,119.959596,0.252525,121.494949,0.0,197.979798,0.0,100.0,5.249608e+05,NaN,NaN,77.000000,23.000000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,98.533333,1849.333333,100.0,0.0,72.214286,285543.071429,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,73881.000000,100.0,1.212273e+11,100.0,5.281163e+11,NaN,NaN,NaN,NaN,100.0,1.992403e+10,100.0,5.166644e+08,100.0,8.811075e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.912846e+12,0.0,0.0,0.0,5.781711,12.527651,9.608388,8.383612e+07,59.956572,49.172486,18.314883,647.871661,0.0,9.115430,53.233673,34.838828,57.618837,1.873701e+09,62.100993,8.332381,35.88755,15829.011222,53.693927,0.0,2.737609,2890.548011,0.0,9.256671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.020779,4.020779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,21.571586,1.167958e+12,0.0,4.041452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,16.263456,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.226455,0.226455,0.0,0.114708,0.0,0.0,4.883987,4.883987,0.433463,5210.902245,15.369785,597.015617,0.468835,569.765601,45.628411,4.670248,35.776322,8.194795e+07,75.849654,0.0,51.598117,2.413159,53.233673,0.0,14.140678,0.0,0.0,4.730983e+05,NaN,NaN,24.041631,24.041631,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.669047,2831.995805,NaN,NaN,2.991747,31008.127333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9824.799745,0.0,1.576552e+10,0.0,7.741505e+10,NaN,NaN,NaN,NaN,0.0,1.954250e+10,0.0,6.266023e+08,0.0,1.021591e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.500594e+11,0.0,0.0,1028.0,0.000000,0.000000,64.000000,0.000000e+00,100.000000,0.000000,84.000000,0.000000,100.0,3.000000,100.000000,0.000000,68.000000,0.000000e+00,100.000000,0.000000,1.00000,3364.000000,100.000000,0.0,90.000000,19.000000,100.0,3.000000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,90.000000,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,60.000000,7.900000e+01,100.0,0.000000,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,27.000000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,98.000000,0.000000,100.0,0.000000,100.0,0.0,59.000000,22.000000,96.000000,0.000000,97.000000,0.000000,97.000000,113.000000,22.000000,22.000000,1.000000,0.000000e+00,100.000000,0.0,100.000000,0.000000,100.000000,0.0,100.000000,0.0,100.0,2.047000e+04,NaN,NaN,60.000000,6.000000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,90.000000,0.000000,100.0,0.0,66.000000,216860.000000,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,0.000000,100.0,6.578600e+04,100.0,3.389100e+04,NaN,NaN,NaN,NaN,100.0,6.105397e+09,100.0,7.358960e+07,100.0,1.587336e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.001563e+12,0.0,0.0,1028.0,5.000000,12.500000,78.750000,4.950886e+06,134.000000,0.000000,84.000000,0.000000,100.0,8.000000,100.000000,0.000000,86.000000,5.172001e+07,128.000000,0.000000,14.00000,75410.750000,100.000000,0.0,98.250000,396.750000,100.0,8.000000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,97.750000,97.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,77.000000,3.000000e+02,100.0,0.000000,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,32.750000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.000000,0.000000,100.0,0.000000,100.0,0.0,66.000000,27.000000,100.000000,0.000000,100.000000,186.000000,100.000000,501.500000,28.000000,27.000000,1.000000,2.288331e+07,100.000000,0.0,100.000000,0.000000,100.000000,0.0,200.000000,0.0,100.0,8.357600e+04,NaN,NaN,68.500000,14.500000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,98.500000,350.500000,100.0,0.0,71.000000,273181.750000,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,75410.000000,100.0,1.220499e+11,100.0,5.064929e+11,NaN,NaN,NaN,NaN,100.0,1.301471e+10,100.0,2.951270e+08,100.0,5.199205e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.001563e+12,0.0,0.0,1028.0,10.000000,24.000000,82.000000,8.525151e+07,252.000000,0.000000,84.000000,0.000000,100.0,10.000000,100.000000,0.000000,95.000000,4.517057e+08,252.000000,0.000000,14.00000,75437.000000,100.000000,0.0,99.500000,873.000000,100.0,10.000000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,94.000000,5.210000e+02,100.0,0.000000,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,38.500000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.000000,0.000000,100.0,0.000000,100.0,0.0,70.000000,30.000000,100.000000,0.000000,100.000000,192.000000,100.000000,531.000000,33.000000,30.000000,1.000000,9.737350e+07,252.000000,0.0,100.000000,0.000000,100.000000,0.0,200.000000,0.0,100.0,4.422200e+05,NaN,NaN,77.000000,23.000000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,100.000000,608.000000,100.0,0.0,72.500000,284654.000000,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,75414.000000,100.0,1.231084e+11,100.0,5.363355e+11,NaN,NaN,NaN,NaN,100.0,1.992403e+10,100.0,5.166644e+08,100.0,8.811075e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,8.001563e+12,0.0,0.0,1028.0,15.000000,33.000000,84.000000,1.612508e+08,252.000000,104.000000,91.000000,0.000000,100.0,14.000000,100.000000,0.000000,96.000000,3.743837e+09,252.000000,18.000000,14.00000,75444.250000,100.000000,0.0,100.000000,2412.000000,100.0,14.250000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,97.000000,1.011482e+12,100.0,3.500000,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,44.250000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.000000,0.000000,100.0,0.000000,100.0,0.0,73.000000,34.000000,100.000000,0.000000,100.000000,197.000000,100.000000,561.000000,41.000000,34.000000,1.000000,1.788656e+08,252.000000,0.0,100.000000,0.000000,100.000000,0.0,200.000000,0.0,100.0,8.796835e+05,NaN,NaN,85.500000,31.500000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,100.000000,2142.000000,100.0,0.0,73.000000,296990.750000,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,75422.000000,100.0,1.249732e+11,100.0,5.656120e+11,NaN,NaN,NaN,NaN,100.0,2.683335e+10,100.0,7.382017e+08,100.0,1.242294e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,8.001563e+12,0.0,0.0,1028.0,19.000000,43.000000,100.000000,2.411366e+08,252.000000,112.000000,236.000000,1835.000000,100.0,66.000000,252.000000,280.000000,252.000000,8.326882e+09,252.000000,18.000000,100.00000,78798.000000,252.000000,0.0,100.000000,11102.000000,100.0,61.000000,NaN,NaN,NaN,NaN,100.0,97.0,100.0,97.0,100.0,0.0,100.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,0.0,NaN,NaN,100.0,108.0,100.0,0.0,100.0,0.0,100.000000,2.022963e+12,100.0,7.000000,NaN,NaN,NaN,NaN,0.0,10.0,NaN,NaN,NaN,NaN,0.0,50.000000,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,100.000000,2.000000,100.0,1.000000,100.0,0.0,78.000000,41.000000,100.000000,48077.000000,252.000000,4364.000000,100.000000,4364.000000,253.000000,41.000000,100.000000,2.411366e+08,252.000000,0.0,252.000000,24.000000,252.000000,0.0,200.000000,0.0,100.0,1.418913e+06,NaN,NaN,94.000000,40.000000,100.0,0.0,100.0,0.0,NaN,NaN,NaN,NaN,100.0,0.0,100.0,0.0,1.0,57966.0,100.000000,11102.000000,100.0,0.0,79.000000,352504.000000,100.0,268.0,NaN,NaN,100.0,1.099512e+14,100.0,4.638565e+11,100.0,120960.0,NaN,NaN,100.0,2.536725e+11,100.0,75440.000000,100.0,1.288321e+11,100.0,6.141010e+11,NaN,NaN,NaN,NaN,100.0,3.374266e+10,100.0,9.597391e+08,100.0,1.603481e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN